---
- name: "Install Java 11"
  apt:
    name: openjdk-11-jdk
    update_cache: yes

- name: "python units install"
  apt:
    name: "libfontconfig"

- name: "python units install"
  apt:
    name: "libncurses5-dev"

- name: "python units install"
  apt:
    name: "libffi-dev"

- name: "python units install"
  apt:
    name: "python3-pip"

- name: "Add Jenkins GPG key"
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: "add jenkins repo"
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: "Install Jenkins server"
  apt:
    name: jenkins
    state: present
    update_cache: yes